export const ActionTypes = {
  GET_ALL_CONTACTS: "GET_ALL_CONTACTS",
  GET_US_CONTACTS: "GET_US_CONTACTS",
  ONLY_EVEN_CONTACTS: "ONLY_EVEN_CONTACTS",
  FETCH_CONTACTS_START: "FETCH_CONTACTS_START",
  FETCH_CONTACTS_STOP: "FETCH_CONTACTS_STOP",
  GET_EVEN_ID_CONTACTS: "GET_EVEN_ID_CONTACTS",
};
